services:
  front:
    build:
      context: ./front
    ports:
      - 5173:5173
    volumes:
      - node_modules:/opt/workdir/node_modules
      - type: bind
        source: ./front
        target: /opt/workdir

  vite_scaffolder:
    build:
      context: .
      dockerfile: Dockerfile.vite
    volumes:
      - type: bind
        source: .
        target: /opt/workdir

volumes:
  node_modules:
